spring.application.name=practica3
spring.datasource.url=jdbc:postgresql://localhost:5432/login
spring.datasource.username=postgres
spring.datasource.password=salsanegra12
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
server.error.include-binding-errors=always
